name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci

      - name: Terraform IaC
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_db: ${{ secrets.DB_NAME }}
          AWS_DEFAULT_REGION: eu-west-2
        id: init
        working-directory: ./deployment
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: ./deployment
        run: terraform validate -no-color

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_db: ${{ secrets.DB_NAME }}
          AWS_DEFAULT_REGION: eu-west-2
        id: plan
        working-directory: ./deployment
        run: terraform plan
    
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_db: ${{ secrets.DB_NAME }}
          AWS_DEFAULT_REGION: eu-west-2
        id: apply
        working-directory: ./deployment
        run: terraform apply -auto-approve

